export const professionalTags = [
  {
    label: "Body Piercing",
    options: [
      { value: "ear_lobe", label: "Ear Lobe Piercing" },
      { value: "helix", label: "Helix Piercing" },
      { value: "tragus", label: "Tragus Piercing" },
      { value: "conch", label: "Conch Piercing" },
      { value: "rook", label: "Rook Piercing" },
      { value: "daith", label: "Daith Piercing" },
      { value: "industrial", label: "Industrial Piercing" },
      { value: "nostril", label: "Nostril Piercing" },
      { value: "septum", label: "Septum Piercing" },
      { value: "bridge", label: "Bridge Piercing" },
      { value: "eyebrow", label: "Eyebrow Piercing" },
      { value: "lip", label: "Lip Piercing (Labret, Monroe, etc.)" },
      { value: "tongue", label: "Tongue Piercing" },
      { value: "smiley_frowny", label: "Smiley/Frowny Piercing" },
      { value: "frenulum", label: "Web (Frenulum) Piercing" },
      { value: "nipple", label: "Nipple Piercing" },
      { value: "navel", label: "Navel (Belly Button) Piercing" },
      { value: "dermal", label: "Dermal/Microdermal Implants" },
      { value: "surface", label: "Surface Piercing" },
      { value: "genital", label: "Genital Piercing" },
      { value: "ear_cartilage", label: "Ear Cartilage Curation" },
      { value: "stretching", label: "Stretching/Gauging Services" },
      { value: "piercing_aftercare", label: "Aftercare Specialist" },
      { value: "titanium_jewelry", label: "Titanium Jewelry" },
      { value: "gold_jewelry", label: "Gold Jewelry" },
      { value: "custom_jewelry", label: "Custom Jewelry Design" },
      { value: "needle_piercing_only", label: "Needle Piercing Only" },
      { value: "piercing_consultation", label: "Piercing Consultation" },
    ],
  },
  {
    label: "Tattoo",
    options: [
      { value: "fine_line", label: "Fine Line" },
      { value: "color_realism", label: "Color Realism" },
      { value: "black_grey_realism", label: "Black & Grey Realism" },
      { value: "american_traditional", label: "American Traditional" },
      { value: "neo_traditional", label: "Neo-Traditional" },
      { value: "japanese_irezumi", label: "Japanese (Irezumi)" },
      { value: "tribal", label: "Tribal" },
      { value: "geometric", label: "Geometric" },
      { value: "watercolor", label: "Watercolor" },
      { value: "blackwork", label: "Blackwork" },
      { value: "dotwork", label: "Dotwork" },
      { value: "script_lettering", label: "Script/Lettering" },
      { value: "illustrative", label: "Illustrative" },
      { value: "new_school", label: "New School" },
      { value: "portrait", label: "Portrait Tattoos" },
      { value: "cover_up", label: "Cover-up Specialist" },
      { value: "abstract", label: "Abstract" },
      { value: "biomechanical", label: "Biomechanical" },
      { value: "surrealism", label: "Surrealism" },
      { value: "sketch_work", label: "Sketch Work" },
      { value: "minimalist", label: "Minimalist Tattoos" },
      { value: "anime_manga", label: "Anime/Manga" },
      { value: "micro_realism", label: "Micro-realism" },
      { value: "hand_poked", label: "Hand-poked/Stick-and-poke" },
      { value: "custom_design", label: "Custom Design" },
      { value: "flash_tattoos", label: "Flash Tattoos" },
      { value: "vegan_ink", label: "Vegan Ink" },
      { value: "tattoo_consultation", label: "Tattoo Consultation" },
      { value: "scar_cover_up", label: "Scar Cover-up" },
    ],
  },
];
